<?php

return [
    'UID' => [
        'Jatim' => "Jatim",
    ],

    'UP3' => [
        'BJG' => 'BJG',
        'BWG' => 'BWG',
        'GSK' => 'GSK',
        'JBR' => 'JBR',
        'KDR' => 'KDR',
        'MDN' => 'MDN',
        'MJK' => 'MJK',
        'MLG' => 'MLG',
        'PKS' => 'PKS',
        'PNG' => 'PNG',
        'PSR' => 'PSR',
        'SBS' => 'SBS',
        'SBB' => 'SBB',
        'SBU' => 'SBU',
        'SDA' => 'SDA',
        'STB' => 'STB',
    ],

    'ULP' => [
        'Ambulu' => 'Ambulu',
        'Ambunten' => 'Ambunten',
        'Asem Bagus' => 'Asem Bagus',
        'Babat' => 'Babat',
        'Balong' => 'Balong',
        'Bangil' => 'Bangil',
        'Bangkalan' => 'Bangkalan',
        'Banyuwangi Kota' => 'Banyuwangi Kota',
        'Batu' => 'Batu',
        'Benjeng' => 'Benjeng',
        'Besuki' => 'Besuki',
        'Blega' => 'Blegal',
        'Blimbing' => 'Bimbing',
        'Blitar' => 'Blitar',
        'Bojonegoro' => 'Bojonegoro',
        'Bondowoso' => 'Bondowoso',
        'Brondong' => 'Brondong',
        'Bululawang' => 'Bululawang',
        'Campur Darat' => 'Campur Darat',
        'Caruban' => 'Caruban',
        'Dampit' => 'Dampit',
        'Darmo Permai' => 'Darmo Permai',
        'Dinoyo' => 'Dinoyo',
        'Dolopo' => 'Dolopo',
        'Dukuh Kupang' => 'Dukuh Kupang',
        'Embong Wungu' => 'Embong Wungu',
        'Gedangan' => 'Gedangan',
        'Genteng' => 'Genteng',
        'Giri' => 'Giri',
        'Gondang Wetan' => 'Gondang Wetan',
        'Gondanglegi' => 'Gondanglegi',
        'Grati' => 'Grati',
        'Indrapura' => 'Indrapura',
        'Jajag' => 'Jajag',
        'Jatirogo' => 'Jatirogo',
        'Jember Kota' => 'Jember Kota',
        'Jombang' => 'Jombang',
        'Kalisat' => 'Kalisat',
        'Kamal' => 'Kamal',
        'Karang Pilang' => 'Karang Pilang',
        'Kebonagung' => 'Kebonagung',
        'Malang' => 'Malang',
        'Pamekasan' => 'Pamekasan',
        'Jatim' => 'Jatim',
    ],

];